### ISSUE TITLE
clini_table and slide_table same file

### ISSUE THREAD

**Issue by victor-moreno** [KatherLab/STAMP#16]
Hi,
I suggest checking if clini_table and slide_table are the same file, the avoid the merge in line 249 of https://github.com/KatherLab/STAMP/tree/main/stamp/modeling/marugoto/transformer/helpers.py

It may be easier to maintain a single file with PATIENT, FILENAME, outcome1, outcome2 ...
Now, the merge finds duplicated names and adds _x _y, then an error is risen in line 252. df.dropna(subset=target_label) doesn't find target_label because it has been renamed in the merge
I managed to use the same file using outcome1_x as target_label

Best regards

Victor

**Comment by Avic3nna** [comment]
Hi Victor, we have kept this separately on purpose specifically for the situation when a patient has multiple slides. Then the overall table blows up, so we decided to keep them separate
