### ISSUE TITLE
UNI model location

### ISSUE THREAD

**Issue by victor-moreno** [KatherLab/STAMP#18]
UNI model specification is inconsistent with CPT:
model_path is ignored and I had to review the code to see that STAMP_RESOURCES_DIR is needed, and the uni model must be in 
$STAMP_RESOURCES_DIR/uni/ and keep folder vit_large_patch16_224.dinov2.uni_mass100k because uni.get.encoder is used

I think model_path in config.yaml could be used to define the assets_dir that now is STAMP_RESOURCES_DIR/uni  for uni.get_encoder

**Comment by Avic3nna** [comment]
Hi Victor, I've removed some unnecessary arguments such as model_path and normalization_template in the latest version.

When installing the latest version of STAMP, all the things are handled implicitly and the user does not have to worry about it anymore.
