### ISSUE TITLE
Unsupported TIFF compression: 7

### ISSUE THREAD

**Issue by suminwei** [KatherLab/STAMP#27]
Hi,
I'm running ```stamp preprocess``` and I'm using .svs files downloaded from TCGA as input. However, I keep on getting the error 

```JPEG compression support is not configured.
Failed loading slide, continuing... Error: Unsupported TIFF compression: 7
```

From reading the protocol online, STAMP supports SVS file formats. I also tried .tiff and .jpeg, but nothing seems to work. I'd appreciate your help!
Thank you,
Lisa

**Comment by Avic3nna** [comment]
Solved - Above error was produce on HPC and their local OpenSlide installation was likely not the right version. Then, used the container (built from container.def) and problems were resolved.
