### ISSUE TITLE
Trouble running stamp preprocess

### ISSUE THREAD

**Issue by suminwei** [KatherLab/STAMP#28]
Hello,
I'm having some trouble running stamp preprocess. I am just testing it on one .svs file right now.

Below is the script I wrote for sbatch submission using SLURM:

```
#!/bin/bash

#SBATCH -c 5                 # request 5 cores
#SBATCH -t 2-00:00:00        # 2 days run time
#SBATCH -p gpu               # use gpu
#SBATCH --gres=gpu:1         # use 1 GPU
#SBATCH --mem 130G           # use 130GB
#SBATCH -o STAMP%j.out       # Send output for each job to file with overall job ID and task ID in the filename
#SBATCH -e STAMP%j.err
#SBATCH --job-name=STAMP_run_0                      # create a short name for your job

singularity run --nv -B /n,/path/to/Software/singularity_containers/STAMP/resources_container/stamp:/opt/miniconda3/envs/hpc_cenv/lib/python3.10/site-packages/stamp /n/app/singularity/containers/liw165/STAMP_container.sif "stamp --config /path/to/ML/analysis/STAMP/config.yaml preprocess"
```
and I get the following error:

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB. GPU
```

**Comment by Avic3nna** [comment]
Looks like your partition doesn't have a (large) GPU. It crashed after trying to allocate 50 megabytes, the model itself is 20 GB or so. 

Maybe it was peaktime on your cluster and there was absolutely no GPU available? 50 MB will never be enough. Otherwise you could also put device="cpu" in the config file instead of "cuda:0" if your cluster doesn't have GPUs.

**Comment by suminwei** [comment]
Hi Omar,
Thank you for the reply!
I'm not sure if this is something I should figure out on my end - but I guess I found it odd that I requested 150GB in the sbatch submission script, and it started running which means it was able to allocate this much resources. But the task still stopped at 50MB.
I can also try changing to CPU or run again today with GPU.
Thank you,
Lisa
________________________________

**Comment by Avic3nna** [comment]
Hi Lisa, the 130GB you requested is for the CPU memory, not the GPU memory
