### ISSUE TITLE
clini_table and slide_table template

### ISSUE THREAD

**Issue by Breeze-Zero** [KatherLab/STAMP#39]
I thought it would be useful to provide a clini_table and slide_table template (containing at least the key elements needed for model training) that would help me apply it to my own data set, otherwise I would have to drill down into the training code to de-reason the table structure.

**Comment by Avic3nna** [comment]
We created a paper with templates and examples + troubleshooting for most of the issues that could occur during execution of the code: https://www.nature.com/articles/s41596-024-01047-2
